<?php
include "includes/session.php";
include "db/conect_database.php";
include "db/crud.php";

if (isset($_SESSION['user_id']) && !empty($_SESSION['user_id'])) {
    header('Location: includes/home.php');
    exit();
}
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>b1t5 ch41n5 - HACKER LOGIN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/hacker-footer.css">
    
    <!-- 🖼️ Hacker Theme Styles 'keep in mind all CSS code was generated by AI' -->
    <style>
        .hacker-footer {
            background: transparent !important;
        }

        body::before {
            content: "";
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: url('https://media.giphy.com/media/oEI9uBYSzLpBK/giphy.gif') center center / cover no-repeat;
            opacity: 0.1;
            z-index: -1;
        }
        /* ===================================
           IMPROVED FONTS
           =================================== */
        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Fira+Code:wght@300;400;500;700&display=swap');
        
        /* Ensure the body background image fills the entire screen */
        body {
            background: url('css/img/anon.jpg') no-repeat center center fixed;
            background-size: cover;
            min-height: 100vh;
            font-family: 'Fira Code', monospace;
            margin: 0; /* Remove default margin */
            padding: 0; /* Remove default padding */
            position: relative;
        }

        /* Adjust the navbar to align properly */
        .navbar {
            z-index: 2; /* Ensure it stays above the background */
            position: sticky; /* Keep it fixed at the top */
            top: 0;
        }

        /* Ensure content starts below the navbar */
        .content-wrapper {
            padding-top: 56px; /* Offset for navbar height */
        }

        /* Hacker blue overlay */
        .hacker-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            background: linear-gradient(135deg, rgba(10,10,26,0.85) 0%, rgba(26,26,58,0.85) 50%, rgba(42,42,90,0.85) 100%);
            z-index: 0;
        }
        /* Command terminal background */
        .terminal-bg {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            z-index: 1;
            pointer-events: none;
            opacity: 0.18;
            font-family: 'Courier New', monospace;
            color: #00ff41;
            font-size: 18px;
            overflow: hidden;
        }
        .terminal-line {
            white-space: pre;
            margin: 0;
            padding-left: 20px;
            font-weight: 600; /* MORE BOLD */
            text-shadow: 
                0 0 10px #00ff41, 
                0 0 15px #00ff41, 
                0 0 5px #00ff41;
            animation: scroll-terminal 15s linear infinite, glow-pulse 2s ease-in-out infinite alternate;
        }
        @keyframes scroll-terminal {
            0% { transform: translateY(0); }
            100% { transform: translateY(-100vh); }
        }
        

        
        /* ===================================
           MAIN CONTAINER
           =================================== */
        .login-container {
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        /* ===================================
           LOGIN CARD
           =================================== */
        .hacker-card {
            background: rgba(0, 0, 0, 0.95); /* More opaque */
            border: 3px solid #00bfff; /* Thicker border */
            border-radius: 15px;
            box-shadow: 
                0 0 30px rgba(0, 191, 255, 0.5),
                inset 0 0 30px rgba(0, 191, 255, 0.2),
                0 0 60px rgba(0, 255, 65, 0.3); /* More glow */
            backdrop-filter: blur(15px);
            max-width: 450px; /* Wider */
            width: 100%;
            /* animation removed so the panel doesn't move */
        }
        
        /* ===================================
           CARD HEADER
           =================================== */
        .hacker-header {
            background: linear-gradient(45deg, #00bfff, #0099cc, #00ffff);
            color: #000;
            text-align: center;
            padding: 25px;
            border-radius: 12px 12px 0 0;
            font-weight: 900; /* EXTRA BOLD */
            font-family: 'Orbitron', monospace;
            text-transform: uppercase;
            letter-spacing: 3px;
            box-shadow: 0 0 20px rgba(0, 191, 255, 0.5);
        }
        
        .hacker-header h3 {
            font-size: 24px !important;
            text-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }
        
        /* ===================================
           LOGIN FORM
           =================================== */
        .login-form {
            padding: 30px;
            color: #00bfff;
        }
        
        .form-control {
            background: rgba(0, 0, 0, 0.9); /* Darker */
            border: 2px solid #00bfff; /* Thicker border */
            color: #00ffff !important; /* Livelier cyan blue */
            border-radius: 10px;
            padding: 15px 20px; /* More padding */
            font-family: 'Fira Code', monospace !important;
            font-size: 16px !important; /* Larger size */
            font-weight: 500 !important; /* MORE BOLD */
            letter-spacing: 1px; /* Spacing between letters */
            transition: all 0.3s ease;
            text-shadow: 0 0 8px #00ffff; /* Glow in the text */
        }
        
        .form-control:focus {
            background: rgba(0, 0, 0, 0.95) !important;
            border-color: #00ffff !important;
            box-shadow: 
                0 0 20px rgba(0, 255, 255, 0.8),
                inset 0 0 20px rgba(0, 255, 255, 0.2) !important;
            color: #00ffff !important;
            text-shadow: 0 0 12px #00ffff !important;
            transform: scale(1.02);
        }
        
        .form-control::placeholder {
            color: rgba(0, 191, 255, 0.7) !important;
            font-family: 'Fira Code', monospace !important;
            font-weight: 400 !important;
            font-style: italic;
        }
        
        /* ===================================
           LOGIN BUTTON
           =================================== */
        .btn-hacker {
            background: linear-gradient(45deg, #00bfff, #0099cc, #00ffff);
            border: none;
            color: #000 !important;
            font-weight: 900 !important; /* EXTRA BOLD */
            text-transform: uppercase;
            letter-spacing: 2px;
            padding: 15px 30px;
            border-radius: 10px;
            font-size: 16px !important;
            transition: all 0.3s ease;
            width: 100%;
            box-shadow: 0 0 20px rgba(0, 191, 255, 0.5);
            animation: button-pulse 2s ease-in-out infinite alternate;
        }
        
        @keyframes button-pulse {
            0% { 
                box-shadow: 0 0 20px rgba(0, 191, 255, 0.5);
                transform: scale(1);
            }
            100% { 
                box-shadow: 0 0 30px rgba(0, 191, 255, 0.8);
                transform: scale(1.05);
            }
        }
        
        .btn-hacker:hover {
            background: linear-gradient(45deg, #0099cc, #00bfff, #00ffff) !important;
            transform: translateY(-3px) scale(1.08) !important;
            box-shadow: 0 8px 25px rgba(0, 191, 255, 0.6) !important;
            color: #000 !important;
        }
        
        /* ===================================
           ERROR ALERTS
           =================================== */
        .error-alert {
            background: rgba(255, 0, 0, 0.1);
            border: 1px solid #ff0000;
            color: #ff4444;
            border-radius: 8px;
            padding: 10px;
            margin-bottom: 20px;
            font-family: 'Courier New', monospace;
            animation: error-blink 1s ease-in-out 3;
        }
        
        @keyframes error-blink {
            0%, 100% { opacity: 1; }
            50%      { opacity: 0.5; }
        }
        
        /* ===================================
           TERMINAL TEXT
           =================================== */
        .terminal-text {
            font-family: 'Fira Code', monospace;
            font-size: 14px;
            font-weight: 600; /* MORE BOLD */
            color: #00ffff;
            margin-bottom: 20px;
            line-height: 1.6;
            text-shadow: 0 0 8px #00ffff;
            animation: terminal-flicker 3s ease-in-out infinite alternate;
        }
        
        @keyframes terminal-flicker {
            0% { opacity: 0.9; }
            100% { opacity: 1; }
        }
        
        /* ===================================
           LINKS
           =================================== */
        .back-link {
            color: #00bfff;
            text-decoration: none;
            font-size: 14px;
            transition: all 0.3s ease;
        }
        
        .back-link:hover {
            color: #0099cc;
            text-shadow: 0 0 5px rgba(0, 191, 255, 0.5);
        }
        
        /* ===================================
           FORM LABELS
           =================================== */
        .form-label {
            color: #00ffff !important;
            font-weight: 700 !important; /* MORE BOLD */
            font-family: 'Orbitron', monospace !important;
            font-size: 14px !important;
            text-transform: uppercase;
            letter-spacing: 2px;
            margin-bottom: 10px !important;
            display: block;
            text-shadow: 0 0 10px #00ffff;
            animation: label-glow 2s ease-in-out infinite alternate;
        }
        
        @keyframes label-glow {
            0% { text-shadow: 0 0 10px #00ffff; }
            100% { text-shadow: 0 0 15px #00ffff, 0 0 25px #00ffff; }
        }
        
        .form-label i {
            margin-right: 10px;
            font-size: 16px;
            color: #ff0080;
            text-shadow: 0 0 8px #ff0080;
        }
    </style>
</head>


<body>
    <!-- Wrapper for the login -->
    <div class="login-wrapper" style="min-height: 100vh;">
        <!-- Hacker blue overlay -->
        <div class="hacker-overlay"></div>
        <!-- Command terminal background -->
        <div class="terminal-bg" id="terminal-bg"></div>

        
        <!-- ===================================
             MAIN CONTAINER
             =================================== -->
        <div class="login-container">
            <div class="hacker-card">


                <!-- HEADER -->
                <div class="hacker-header">
                    <i class="bi bi-shield-lock"></i>
                    <h3 class="mb-0">D4RKROOM</h3>
                    <small>site for excluded users</small>
                </div>


                <!-- FORM -->
                <div class="login-form">

                    <!-- TERMINAL TEXT -->
                    <div class="terminal-text">
                        > Initializing secure connection...<br>
                        > Encryption protocol: ACTIVE<br>
                        > Please enter your credentials<br>
                        <span style="color: #00bfff;">></span> 
                        <span class="text-warning">_</span>
                    </div>
                    



                    <!-- ERROR MESSAGE -->
                    <?php if (isset($error)): ?>
                        <div class="error-alert">
                            <i class="bi bi-exclamation-triangle"></i>
                            <?php echo htmlspecialchars($error); ?>
                        </div>
                    <?php endif; ?>
                    

                    <!-- LOGIN FORM -->
                    <form method="POST" action="includes/home.php">
                        
                        <!-- USER ID FIELD -->
                        <div class="mb-3">
                            <label for="hacker_user" class="form-label">
                                <i class="bi bi-person-badge"></i> USERNAME
                            </label>
                            <input type="text" class="form-control" id="hacker_user" 
                                    name="hacker_user" placeholder="Enter your user "
                                   required autocomplete="username">
                        </div>
                        
                        <!-- PASSWORD FIELD -->
                        <div class="mb-4">
                            <label for="password" class="form-label">
                                <i class="bi bi-key"></i> PASSWORD
                            </label>
                            <input type="password" class="form-control" 
                                   id="password" name="password" 
                                   placeholder="Enter access code"
                                   required autocomplete="current-password">
                        </div>
                        
                        <!-- LOGIN BUTTON -->
                        <div class="d-grid mb-3">
                            <button type="submit" name="login" class="btn btn-hacker">
                                <i class="bi bi-unlock"></i> INITIATE ACCESS
                            </button>
                        </div>
                        
                    </form>
                    
                    <!-- RETURN LINK -->
                    <div class="text-center">
                        <a href="index.php" class="back-link">
                            <i class="bi bi-arrow-left"></i> Back to Main System
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- ===================================
         SCRIPTS
         =================================== -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <script>

        // Animated command terminal background
        const terminalLines = [
            'Initializing system... [OK]',
            'Loading modules: crypto, net, ai... [OK]',
            'Establishing secure connection...',
            'Running diagnostic: memory scan...',
            'Accessing credentials database...',
            'Verifying user identity...',
            'Injecting encryption keys...',
            'Protocol handshake: success',
            'Monitoring network traffic...',
            'Analyzing threat vectors...',
            'Compiling access logs...',
            'System status: SECURE',
            'Awaiting user input...',
            'root@b1t5ch41n5:~$ sudo access --level=admin',
            'root@b1t5ch41n5:~$ ./run_hack.sh',
            'root@b1t5ch41n5:~$ tail -f /var/log/auth.log',
            'root@b1t5ch41n5:~$ nmap -A 192.168.1.1',
            'root@b1t5ch41n5:~$ ssh -i id_rsa user@server',
            'root@b1t5ch41n5:~$ echo "ACCESS GRANTED"',
        ];
        function renderTerminalBg() {
            const container = document.getElementById('terminal-bg');
            container.innerHTML = '';
            for (let i = 0; i < 12; i++) {
                const line = document.createElement('div');
                line.className = 'terminal-line';
                line.textContent = terminalLines[Math.floor(Math.random() * terminalLines.length)];
                line.style.top = (i * 7 + 10) + 'vh';
                container.appendChild(line);
            }
        }
        renderTerminalBg();
        setInterval(renderTerminalBg, 8000);
        // ===================================
        // AUTOMATIC FOCUS ON FIRST FIELD
        // ===================================
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('user_id').focus();
        });
    </script>
    <footer class="hacker-footer py-5">
        <?php include "includes/footer.php"; ?>
    </footer>
</body>
</html>